name: Generate Snake

# GitHub Actions'ın hangi zamanlarda çalışacağını belirtiyoruz
on:
  schedule:
    # her 6 saatte bir çalışacak cron ifadesi
    - cron: "0 */6 * * *"
  workflow_dispatch:  # Bu satır, manuel olarak da çalıştırılabilmesini sağlar.

jobs:
  build:
    runs-on: ubuntu-latest  # Bu iş, Ubuntu işletim sistemi üzerinde çalışacak.

    steps:
    # Repo içeriğini çekiyoruz
    - name: Checkout repository
      uses: actions/checkout@v2

    # Platane/snakes action'ını kullanarak katkı grafiğini oluşturuyoruz
    - name: Generate Snake GIF
      uses: Platane/snk@v3  # Güncel versiyon
      with:
        github_user_name: denizumur  # GitHub kullanıcı adınız
        gif_out_path: dist/github-contribution-grid-snake.gif  # GIF çıktısının yolu
        svg_out_path: dist/github-contribution-grid-snake.svg  # SVG çıktısının yolu

    # Git durumunu kontrol et
    - name: Show git status
      run: git status

    # Değişiklikleri ana dala (master) push et
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0  # Push işlemi için doğru versiyon
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token'ı ile push
        branch: output  # Değişikliklerin çıkacağı branch
        force: true

    # GitHub Pages üzerinden çıktıyı yayınlama
    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.1.3
      with:
        target_branch: output  # Çıktının yayınlanacağı branch
        build_dir: dist  # Çıktıların bulunduğu dizin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token'ı
