name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Platane/snakes action'ı ile grafiği oluştur
    - name: Generate Snake GIF
      uses: Platane/snk@v3
      with:
        github_user_name: denizumur
        gif_out_path: dist/github-contribution-grid-snake.gif
        svg_out_path: dist/github-contribution-grid-snake.svg

    # Dist dizinini oluştur
    - name: Create dist directory
      run: mkdir -p dist

    # Dizin içeriğini kontrol et
    - name: Check dist directory contents
      run: ls dist

    # Git durumunu kontrol et
    - name: Show git status
      run: git status

    # Değişiklikleri master branch'ine push et
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: output
        force: true

    # GitHub Pages üzerine deploy et
    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.1.3
      with:
        target_branch: output
        build_dir: dist  # Burada dist dizini belirtiliyor
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
